-- ELIMINAR TABLAS EXISTENTES

DROP TABLE if exists stage_00;
-- CREACION DE TABLAS

CREATE TABLE stage_00
(
	id_stage      INTEGER NOT NULL,
    dato_01   TEXT NULL,
dato_02   TEXT NULL,
dato_03   TEXT NULL,
dato_04   TEXT NULL,
dato_05   TEXT NULL,
dato_06   TEXT NULL,
dato_07   TEXT NULL,
dato_08   TEXT NULL,
dato_09   TEXT NULL,
dato_10   TEXT NULL,
dato_11   TEXT NULL,
dato_12   TEXT NULL,
dato_13   TEXT NULL,
dato_14   TEXT NULL,
dato_15   TEXT NULL,
dato_16   TEXT NULL,
dato_17   TEXT NULL,
dato_18   TEXT NULL,
dato_19   TEXT NULL,
dato_20   TEXT NULL,
dato_21   TEXT NULL,
dato_22   TEXT NULL,
dato_23   TEXT NULL,
dato_24   TEXT NULL,
dato_25   TEXT NULL,
dato_26   TEXT NULL,
dato_27   TEXT NULL,
dato_28   TEXT NULL,
dato_29   TEXT NULL,
dato_30   TEXT NULL,
dato_31   TEXT NULL,
dato_32   TEXT NULL,
dato_33   TEXT NULL,
dato_34   TEXT NULL,
dato_35   TEXT NULL,
dato_36   TEXT NULL,
dato_37   TEXT NULL,
dato_38   TEXT NULL,
dato_39   TEXT NULL,
dato_40   TEXT NULL,
dato_41   TEXT NULL,
dato_42   TEXT NULL,
dato_43   TEXT NULL,
dato_44   TEXT NULL,
dato_45   TEXT NULL,
dato_46   TEXT NULL,
dato_47   TEXT NULL,
dato_48   TEXT NULL,
dato_49   TEXT NULL,
dato_50   TEXT NULL,
dato_51   TEXT NULL,
dato_52   TEXT NULL,
dato_53   TEXT NULL,
dato_54   TEXT NULL,
dato_55   TEXT NULL,
dato_56   TEXT NULL,
dato_57   TEXT NULL,
dato_58   TEXT NULL,
dato_59   TEXT NULL,
dato_60   TEXT NULL,
dato_61   TEXT NULL,
dato_62   TEXT NULL,
dato_63   TEXT NULL,
dato_64   TEXT NULL,
dato_65   TEXT NULL,
dato_66   TEXT NULL,
dato_67   TEXT NULL,
dato_68   TEXT NULL,
dato_69   TEXT NULL,
dato_70   TEXT NULL,
dato_71   TEXT NULL,
dato_72   TEXT NULL,
dato_73   TEXT NULL,
dato_74   TEXT NULL,
dato_75   TEXT NULL,
dato_76   TEXT NULL,
dato_77   TEXT NULL,
dato_78   TEXT NULL,
dato_79   TEXT NULL,
dato_80   TEXT NULL,
dato_81   TEXT NULL,
dato_82   TEXT NULL,
dato_83   TEXT NULL,
dato_84   TEXT NULL,
dato_85   TEXT NULL,
dato_86   TEXT NULL,
dato_87   TEXT NULL,
dato_88   TEXT NULL,
dato_89   TEXT NULL,
dato_90   TEXT NULL,
dato_91   TEXT NULL,
dato_92   TEXT NULL,
dato_93   TEXT NULL,
dato_94   TEXT NULL,
dato_95   TEXT NULL,
dato_96   TEXT NULL,
dato_97   TEXT NULL,
dato_98   TEXT NULL,
dato_99   TEXT NULL,
dato_100   TEXT NULL,
dato_101   TEXT NULL,
dato_102   TEXT NULL,
dato_103   TEXT NULL,
dato_104   TEXT NULL,
dato_105   TEXT NULL,
dato_106   TEXT NULL,
dato_107   TEXT NULL,
dato_108   TEXT NULL,
dato_109   TEXT NULL,
dato_110   TEXT NULL,
dato_111   TEXT NULL,
dato_112   TEXT NULL,
dato_113   TEXT NULL,
dato_114   TEXT NULL,
dato_115   TEXT NULL,
dato_116   TEXT NULL,
dato_117   TEXT NULL,
dato_118   TEXT NULL,
dato_119   TEXT NULL,
dato_120   TEXT NULL,
dato_121   TEXT NULL,
dato_122   TEXT NULL,
dato_123   TEXT NULL,
dato_124   TEXT NULL,
dato_125   TEXT NULL,
dato_126   TEXT NULL,
dato_127   TEXT NULL,
dato_128   TEXT NULL,
dato_129   TEXT NULL,
dato_130   TEXT NULL,
dato_131   TEXT NULL,
dato_132   TEXT NULL,
dato_133   TEXT NULL,
dato_134   TEXT NULL,
dato_135   TEXT NULL,
dato_136   TEXT NULL,
dato_137   TEXT NULL,
dato_138   TEXT NULL,
dato_139   TEXT NULL,
dato_140   TEXT NULL,
dato_141   TEXT NULL,
dato_142   TEXT NULL,
dato_143   TEXT NULL,
dato_144   TEXT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin;  
/* AL UTILIZAR UTF8 Y UTO8_BIN PODEMOS DISTINGUIR ENTRE TILDES Y NO TILDES */

ALTER TABLE stage_00
ADD PRIMARY KEY (id_stage);

ALTER TABLE stage_00
MODIFY id_stage INT NOT NULL AUTO_INCREMENT;


/* CONOCER LOS DETALLE DE UNA TABLA */
SHOW TABLE STATUS where name like 'stage_00';
/**/


